const ActionTypes = {
  RECEIVE_ACTIVITIES: 'RECEIVE_ACTIVITIES',
  RECEIVE_BREAKFAST: 'RECEIVE_BREAKFAST',
  RECEIVE_LUNCH: 'RECEIVE_LUNCH',
  RECEIVE_DINNER: 'RECEIVE_DINNER',
  RECEIVE_RESTAURANTS: 'RECEIVE_RESTAURANTS',
  RECEIVED_DB_ERROR: 'RECEIVED_DB_ERROR',
  RECEIVED_NEW_CLIENT: 'RECEIVED_NEW_CLIENT',
  RECEIVED_UPDATED_CLIENT: 'RECEIVED_UPDATED_CLIENT',

  SENT_EMAIL: 'SENT_EMAIL',

  CLIENT_ADD_MALE: 'WHO_ADD_MALE',
  CLIENT_ADD_FEMALE: 'WHO_ADD_FEMALE',
  CLIENT_ADD_KID: 'WHO_ADD_KID',

  WHO_ADD_MALE: 'WHO_ADD_MALE',
  WHO_ADD_FEMALE: 'WHO_ADD_FEMALE',
  WHO_ADD_KID: 'WHO_ADD_KID',
};

export default ActionTypes;
